[package]
name = "day25"
version = "0.1.0"
authors = ["Vesco Claudio <claudio.vesco@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
